services:
  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hotel
    ports:
      - "3306:3306"
    networks:
      - food-network

  eureka-server:
    build: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    depends_on:
      - mysql
    networks:
      - food-network

  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "2006:2006"
    depends_on:
      - eureka-server
      - mysql
    networks:
      - food-network

  restaurant-service:
    build: ./restaurant-service
    container_name: restaurant-service
    ports:
      - "2003:2003"
    depends_on:
      - eureka-server
      - mysql
    networks:
      - food-network

  order-service:
    build: ./order-service
    container_name: order-service
    ports:
      - "2004:2004"
    depends_on:
      - eureka-server
      - mysql
    networks:
      - food-network

  payment-service:
    build: ./payment-service
    container_name: payment-service
    ports:
      - "2005:2005"
    depends_on:
      - eureka-server
      - mysql
    networks:
      - food-network

networks:
  food-network:
    driver: bridge
